### ISSUE TITLE
Cherry trees suffocate plains biomes

### ISSUE THREAD

**Issue by Sunconure11** [SWUTM/Trails_and_Tales_Fabric#1]
They completely overtake said biome, ruining the look. Furthermore, cherry trees were part of their own biome. I suggest using Terrablender to add said biome.

https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric

**Comment by SWUTM** [comment]
This was a temporary fix just so we're almost done with a major mod update. And there it has already been fixed.
